Combine test workflows

diff --git a/.github/workflows/nethermind-tests.yml b/.github/workflows/nethermind-tests.yml
--- a/.github/workflows/nethermind-tests.yml
+++ b/.github/workflows/nethermind-tests.yml
@@ -9,15 +9,25 @@ on:
   push:
     branches: [master]
   workflow_dispatch:
+    inputs:
+      coverage:
+        default: false
+        description: Collect coverage
+        required: false
+        type: boolean
 
 env:
+  COLLECT_COVERAGE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event.inputs.coverage }}
   DOTNET_VERSION: 7
 
 jobs:
-  nethermind:
+  nethermind-tests:
     name: Run ${{ matrix.project }}
     runs-on: ubuntu-latest
     continue-on-error: true
+    outputs:
+      collect_coverage: ${{ env.COLLECT_COVERAGE }}
+      failed: ${{ steps.test-failure.outputs.failed }}
     strategy:
       matrix:
         project:
@@ -76,12 +86,36 @@ jobs:
         sudo apt-get update
         sudo apt-get install libsnappy-dev -y --no-install-recommends
     - name: ${{ matrix.project }}
-      run: dotnet test src/Nethermind/${{ matrix.project }} -c release
+      id: test
+      run: |
+        dotnet test src/Nethermind/${{ matrix.project }} -c release \
+          ${{ env.COLLECT_COVERAGE == 'true' && '-p:CollectCoverage=true -p:CoverletOutputFormat=opencover' || '' }}
+    - name: Check for failure
+      id: test-failure
+      if: failure() && steps.test.outcome != 'success'
+      run: echo "failed=true" >> $GITHUB_OUTPUT
+    - name: Upload coverage report
+      if: env.COLLECT_COVERAGE == 'true'
+      uses: actions/upload-artifact@v3
+      with:
+        name: ${{ matrix.project }}-coverage
+        path: src/Nethermind/${{ matrix.project }}/coverage.opencover.xml
+    
 
-  ethereum:
+  nethermind-tests-status:
+    name: Nethermind tests
+    needs: nethermind-tests
+    runs-on: ubuntu-latest
+    steps:
+    - name: Ensure tests passed
+      run: exit ${{ needs.nethermind-tests.outputs.failed == 'true' && '1' || '0' }}
+
+  ethereum-tests:
     name: Run ${{ matrix.project }}
     runs-on: ubuntu-latest
     continue-on-error: true
+    outputs:
+      failed: ${{ steps.test-failure.outputs.failed }}
     strategy:
       matrix:
         project:
@@ -114,4 +148,44 @@ jobs:
         sudo apt-get update
         sudo apt-get install libsnappy-dev -y --no-install-recommends
     - name: ${{ matrix.project }}
-      run: dotnet test src/Nethermind/${{ matrix.project }} -c release
+      id: test
+      run: |
+        dotnet test src/Nethermind/${{ matrix.project }} -c release \
+          ${{ env.COLLECT_COVERAGE == 'true' && '-p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude="[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*%2c[Ethereum.Test.Base]*"' || '' }}
+    - name: Check for failure
+      id: test-failure
+      if: failure() && steps.test.outcome != 'success'
+      run: echo "failed=true" >> $GITHUB_OUTPUT
+    - name: Upload coverage report
+      if: env.COLLECT_COVERAGE == 'true'
+      uses: actions/upload-artifact@v3
+      with:
+        name: ${{ matrix.project }}-coverage
+        path: src/Nethermind/${{ matrix.project }}/coverage.opencover.xml
+        retention-days: 1
+
+  ethereum-tests-status:
+    name: Ethereum tests
+    needs: ethereum-tests
+    runs-on: ubuntu-latest
+    steps:
+    - name: Ensure tests passed
+      run: exit ${{ needs.ethereum-tests.outputs.failed == 'true' && '1' || '0' }}
+
+  codecov-upload:
+    name: Upload Codecov reports
+    continue-on-error: true
+    if: needs.nethermind-tests.outputs.collect_coverage == 'true'
+    needs: [nethermind-tests-status, ethereum-tests-status]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download coverage reports
+        uses: actions/download-artifact@v3
+        with:
+          path: .coverage
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          name: codecov-nethermind
+          directory: .coverage
