Add test inputs checksum validation

diff --git a/.github/workflows/stateless-tests.yml b/.github/workflows/stateless-tests.yml
--- a/.github/workflows/stateless-tests.yml
+++ b/.github/workflows/stateless-tests.yml
@@ -45,14 +45,21 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        input:
-          - 150026.bin
-          - 24721542.bin
-          - 24723632.bin
-          - 24723668.bin
-          - 24772857.bin
-          - 24777027.bin
-          - 24777988.bin
+        include:
+          - input: 150026.bin
+            hash: 39cadfc5f37f60c93bb39c9ca2a6db651f7e0f6de1d32177bdedf07c72005fd7
+          - input: 24721542.bin
+            hash: f7075aff304f5011d4e97d759ed30780f65ad8533786f3164f894628686c865d
+          - input: 24723632.bin
+            hash: a61f086b06a477f66944419904b0095f110a74dcca9b183c209300741f143407
+          - input: 24723668.bin
+            hash: 603c28f63cb3fa69206e941027f0af811d24ab062c8188edf32cfa564b94b82e
+          - input: 24772857.bin
+            hash: 5b314cb62f825ad87e1527f1ffb510453b4e3e67ab800e2984483e82214ddd15
+          - input: 24777027.bin
+            hash: 1f739f2c35965e32db367034143dab6b39895b1cc3bca852f80144342c501596
+          - input: 24777988.bin
+            hash: f92a634fe3aec70f825beb49841c2503b810fecf3a1d32beb63eef97519fbe6d
     steps:
       - name: Check out repository
         uses: actions/checkout@v6
@@ -68,10 +75,11 @@ jobs:
         run: |
           curl -sSL "https://us-southeast-1.linodeobjects.com/zktests/${{ matrix.input }}" \
             -o "${{ matrix.input }}"
+          echo "${{ matrix.hash }}  ${{ matrix.input }}" | sha256sum --status -c - || \
+            { echo "Checksum failed"; exit 1; }
 
       - name: Test Nethermind guest
         timeout-minutes: 5
         working-directory: src/Nethermind/Nethermind.Stateless.ZiskGuest
         run: |
-          set -o pipefail
           make run INPUT="${{ matrix.input }}"
