Ensure that logs will check only execution

diff --git a/.github/workflows/sync-testnets.yml b/.github/workflows/sync-testnets.yml
--- a/.github/workflows/sync-testnets.yml
+++ b/.github/workflows/sync-testnets.yml
@@ -67,16 +67,16 @@ jobs:
         working-directory: sedge
         run: docker compose logs
         
-      - name: Verify health of a node
+      - name: Verify health of a Nethermind client
         working-directory: sedge
         run: |
-          countValid=$(docker compose logs | grep -c -E "Valid. Result of a new payload:")
+          countValid=$(docker compose logs execution | grep -c -E "Valid. Result of a new payload:")
           if [ $countValid -lt 1 ]; then
             echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well."
             exit 1
           fi
           
-          count=$(docker compose logs | grep -c -E "Invalid|Exception")
+          count=$(docker compose logs execution | grep -c -E "Invalid|Exception")
           if [ $count -gt 0 ]; then
             echo "Error: Lines found for 'Invalid' or 'Exception'"
             docker compose logs | grep -E "Invalid|Exception" && exit 2
@@ -142,17 +142,17 @@ jobs:
         working-directory: sedge
         run: docker compose logs
           
-      - name: Verify health of a node
+      - name: Verify health of a Nethermind client
         working-directory: sedge
         run: |
-          countValid=$(docker compose logs | grep -c -E "Valid. Result of a new payload:")
+          countValid=$(docker compose logs execution | grep -c -E "Valid. Result of a new payload:")
           if [ $countValid -lt 1 ]; then
             echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well."
             exit 1
           fi
           
-          count=$(docker compose logs | grep -c -E "Invalid|Exception")
+          count=$(docker compose logs execution | grep -c -E "Invalid|Exception")
           if [ $count -gt 0 ]; then
             echo "Error: Lines found for 'Invalid' or 'Exception'"
-            docker compose logs | grep -E "Invalid|Exception" && exit 2
+            docker compose logs execution | grep -E "Invalid|Exception" && exit 2
           fi
