add logging back

diff --git a/.github/workflows/sync-testnets.yml b/.github/workflows/sync-testnets.yml
--- a/.github/workflows/sync-testnets.yml
+++ b/.github/workflows/sync-testnets.yml
@@ -55,58 +55,62 @@ jobs:
                   echo 'Running sedge...'
                   docker compose up -d
 
-            - name: Wait for Chiado to sync
-              id: wait
-              timeout-minutes: 90
+            # - name: Wait for Chiado to sync
+            #   id: wait
+            #   timeout-minutes: 90
+            #   run: |
+            #       set +e
+
+            #       declare -A bad_logs
+            #       bad_logs["Invalid"]=1
+            #       bad_logs["Exception"]=1
+            #       bad_logs["Corrupted"]=1
+
+            #       declare -A good_logs
+            #       good_logs["Synced chain Head"]=0
+            #       good_logs["Processed"]=0
+
+            #       declare -A required_count
+            #       required_count["Synced chain Head"]=20
+            #       required_count["Processed"]=20
+
+            #       echo "Starting Docker logs monitoring..."
+            #       docker logs -f sedge-execution-client | while read -r line; do
+            #         echo "$line"
+
+            #         for bad_log in "${!bad_logs[@]}"; do
+            #           if [[ "$line" == *"$bad_log"* ]]; then
+            #             echo "Error: $bad_log found in Docker logs."
+            #             exit 1
+            #           fi
+            #         done
+
+            #         for good_log in "${!good_logs[@]}"; do
+            #           if [[ "$line" == *"$good_log"* ]]; then
+            #             ((good_logs["$good_log"]++))
+            #           fi
+            #         done
+
+            #         # Check if all good logs have reached the required count
+            #         all_reached_required_count=true
+            #         for good_log in "${!good_logs[@]}"; do
+            #           if [[ ${good_logs[$good_log]} -lt ${required_count[$good_log]} ]]; then
+            #             all_reached_required_count=false
+            #             break
+            #           fi
+            #         done
+
+            #         if $all_reached_required_count; then
+            #           echo "All required logs found."
+            #           break
+            #         fi
+            #       done
+
+            #       echo "Node is synced."
+            - name: "Docker logs"
+              working-directory: sedge
               run: |
-                  set +e
-
-                  declare -A bad_logs
-                  bad_logs["Invalid"]=1
-                  bad_logs["Exception"]=1
-                  bad_logs["Corrupted"]=1
-
-                  declare -A good_logs
-                  good_logs["Synced chain Head"]=0
-                  good_logs["Processed"]=0
-
-                  declare -A required_count
-                  required_count["Synced chain Head"]=20
-                  required_count["Processed"]=20
-
-                  echo "Starting Docker logs monitoring..."
-                  docker logs -f sedge-execution-client | while read -r line; do
-                    echo "$line"
-
-                    for bad_log in "${!bad_logs[@]}"; do
-                      if [[ "$line" == *"$bad_log"* ]]; then
-                        echo "Error: $bad_log found in Docker logs."
-                        exit 1
-                      fi
-                    done
-
-                    for good_log in "${!good_logs[@]}"; do
-                      if [[ "$line" == *"$good_log"* ]]; then
-                        ((good_logs["$good_log"]++))
-                      fi
-                    done
-
-                    # Check if all good logs have reached the required count
-                    all_reached_required_count=true
-                    for good_log in "${!good_logs[@]}"; do
-                      if [[ ${good_logs[$good_log]} -lt ${required_count[$good_log]} ]]; then
-                        all_reached_required_count=false
-                        break
-                      fi
-                    done
-
-                    if $all_reached_required_count; then
-                      echo "All required logs found."
-                      break
-                    fi
-                  done
-
-                  echo "Node is synced."
+                  docker compose logs -f
 
     sepolia:
         name: "Run sync of sepolia testnet"
