Change approach of checking to logs based

diff --git a/.github/workflows/sync-testnets.yml b/.github/workflows/sync-testnets.yml
--- a/.github/workflows/sync-testnets.yml
+++ b/.github/workflows/sync-testnets.yml
@@ -55,87 +55,43 @@ jobs:
       - name: Wait for Chiado to sync
         id: wait
         timeout-minutes: 90
-        run: |        
-          set +e
-          
-          # Check if Docker container is running
-          MAX_RETRIES=10
-          RETRY_COUNT=0
-          while [[ ! "$(docker inspect -f '{{.State.Status}}' sedge-execution-client 2>/dev/null)" =~ "running" ]] && [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
-            echo "Docker container 'sedge-execution-client' is not running. Retrying in 10 seconds..."
-            let "RETRY_COUNT+=1"
-            sleep 10
-          done
-      
-          if [[ ! "$(docker inspect -f '{{.State.Status}}' sedge-execution-client 2>/dev/null)" =~ "running" ]]; then
-            echo "Error: Docker container 'sedge-execution-client' is not running after $MAX_RETRIES attempts."
-            exit 404
-          fi
-          
-          # Check readiness of the service
-          RETRY_COUNT=0
-          while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
-            RESPONSE=$(curl -s --data '{"method":"eth_syncing","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" localhost:8545)
-            if [[ $? -eq 0 ]] && [[ -n "$RESPONSE" ]]; then
-              break
-            else
-              echo "Service not ready. Retrying in 10 seconds..."
-              let "RETRY_COUNT+=1"
-              sleep 10
-            fi
-          done
-          
-          if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
-            echo "Error: Service not ready after $MAX_RETRIES attempts."
-            exit 403
-          fi
-      
-          SYNCING_RESULT=""
-          DEBUG_RESULT=""
-          while [[ "$SYNCING_RESULT" != "false" ]] || [[ "$DEBUG_RESULT" != *"WaitingForBlock"* ]]; do
-            sleep 10
-            RESPONSE_SYNCING=$(curl -s --data '{"method":"eth_syncing","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" localhost:8545)
-            SYNCING_RESULT=$(echo $RESPONSE_SYNCING | jq .result)
-            echo "eth_syncing endpoint response: $RESPONSE_SYNCING"
-        
-            RESPONSE_DEBUG=$(curl -s --data '{"method":"debug_getSyncStage","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" localhost:8545)
-            DEBUG_RESULT=$(echo $RESPONSE_DEBUG | jq -r .result)
-            echo "debug_getSyncStage endpoint response: $RESPONSE_DEBUG"
-      
-          done
-          echo "Sedge is synced."
-                
-      - name: Display Docker logs        
-        working-directory: sedge
-        run: docker compose logs
-        if: steps.wait.outcome == 'success' || steps.wait.outcome == 'failure'
-        
-      - name: Verify health of a node
-        if: steps.wait.outcome == 'success'
-        working-directory: sedge
         run: |
           set +e
-          
-          dockerLogs=$(docker compose logs execution 2>/dev/null)
-
-          validLines=$(echo "$dockerLogs" | grep -E "Valid. Result of a new payload:")
-          countValid=$(if [ -z "$validLines" ]; then echo 0; else echo "$validLines" | wc -l; fi)
-          if [ $countValid -lt 1 ]; then
-            echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well."
-            exit 20
-          fi
-          
-          invalidLines=$(echo "$dockerLogs" | grep -E "Invalid|Exception")
-          countInvalid=$(if [ -z "$invalidLines" ]; then echo 0; else echo "$invalidLines" | wc -l; fi)
-          if [ $countInvalid -gt 0 ]; then
-            echo "Error: Lines found for 'Invalid' or 'Exception'"
-            echo "$invalidLines"
-            exit 30
-          fi
-          
-          # If the script reaches this point, it means there were valid lines and no invalid lines.
-          echo "Valid lines:"
-          echo "$validLines"
+      
+          declare -A bad_logs
+          bad_logs["Invalid"]=1
+          bad_logs["Exception"]=1
+          bad_logs["Corrupted"]=1
+      
+          declare -A good_logs
+          good_logs["Valid. Result of a new payload:"]=1
+          good_logs["WaitingForBlock"]=1
+      
+          declare -A found_good_logs
+      
+          echo "Starting Docker logs monitoring..."
+          docker logs -f sedge-execution-client | while read -r line; do
+            echo "$line"
+      
+            for bad_log in "${!bad_logs[@]}"; do
+              if [[ "$line" == *"$bad_log"* ]]; then
+                echo "Error: $bad_log found in Docker logs."
+                exit 1
+              fi
+            done
+      
+            for good_log in "${!good_logs[@]}"; do
+              if [[ "$line" == *"$good_log"* ]]; then
+                found_good_logs["$good_log"]=1
+              fi
+            done
+      
+            # Check if all good logs are found
+            if [[ ${#good_logs[@]} -eq ${#found_good_logs[@]} ]]; then
+              echo "Node is synced."
+              break
+            fi
+          done
           
   sepolia:
     name: "Run sync of sepolia testnet"
@@ -185,17 +141,19 @@ jobs:
           
       - name: Wait for Sepolia to sync
         id: wait
-        timeout-minutes: 1
         run: |
           set +e
       
           declare -A bad_logs
           bad_logs["Invalid"]=1
           bad_logs["Exception"]=1
+          bad_logs["Corrupted"]=1
       
-          good_logs=("Valid. Result of a new payload:" "WaitingForBlock")
+          declare -A good_logs
+          good_logs["Valid. Result of a new payload:"]=1
+          good_logs["WaitingForBlock"]=1
       
-          found_good_logs=()
+          declare -A found_good_logs
       
           echo "Starting Docker logs monitoring..."
           docker logs -f sedge-execution-client | while read -r line; do
@@ -208,16 +166,15 @@ jobs:
               fi
             done
       
-            for good_log in "${good_logs[@]}"; do
+            for good_log in "${!good_logs[@]}"; do
               if [[ "$line" == *"$good_log"* ]]; then
-                found_good_logs+=("$good_log")
+                found_good_logs["$good_log"]=1
               fi
             done
-          
+      
             # Check if all good logs are found
             if [[ ${#good_logs[@]} -eq ${#found_good_logs[@]} ]]; then
-              echo "Sedge is synced."
+              echo "Node is synced."
               break
             fi
           done
-
