Add Verify for chiado and fix comment

diff --git a/.github/workflows/sync-testnets.yml b/.github/workflows/sync-testnets.yml
--- a/.github/workflows/sync-testnets.yml
+++ b/.github/workflows/sync-testnets.yml
@@ -13,8 +13,6 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-        with:
-          ref: ${{ github.ref }}
           
       - name: Configure settings
         id: settings
@@ -64,6 +62,25 @@ jobs:
           done
           sleep 60
           echo "Sedge is synced."
+      
+      - name: Verify health of a node
+        run: |
+          countValid=$(docker compose logs | grep -c -E "Valid.")
+          countWaitingForBlock=$(docker compose logs | grep -c -E "WaitingForBlock")
+          if [ $countValid -lt 1 ]; then
+            echo "Error: No lines found for 'Valid.' - probably node is not progressing well."
+            exit 1
+          fi
+          if [ $countWaitingForBlock -lt 1 ]; then
+            echo "Error: No lines found for 'WaitingForBlock' - probably node is not progressing well."
+            exit 1
+          fi
+          
+          count=$(docker-compose logs --no-color | grep -c -E "Invalid|Exception")
+          if [ $count -gt 0 ]; then
+            echo "Error: Lines found for 'Invalid' or 'Exception'"
+            exit 1
+          fi
           
       - name: Display Docker logs        
         working-directory: sedge
@@ -75,8 +92,6 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-        with:
-          ref: ${{ github.ref }}
           
       - name: Configure settings
         id: settings
