[Tests] Fix scenario where nethermind stops before capturing extra logs

diff --git a/.github/workflows/sync-supported-chains.yml b/.github/workflows/sync-supported-chains.yml
--- a/.github/workflows/sync-supported-chains.yml
+++ b/.github/workflows/sync-supported-chains.yml
@@ -219,7 +219,7 @@ jobs:
           docker logs -f "$container_name" | while read -r line; do
             echo "$line"
           
-            if [[ "$line" == *"All done"* ]]; then
+            if [[ "$line" == *"Nethermind is shut down"* ]]; then
               echo "Unexpected termination detected: $line"
               exit 1
             fi
@@ -262,6 +262,11 @@ jobs:
               exit 0
             fi
           done
+
+          if [ "$found_bad_log" = true ]; then
+            echo "Error detected, but the logs stopped unexpectedly. Exiting."
+            exit 1
+          fi
           
       - name: Get Consensus Logs
         if: always() && matrix.config.network != 'joc-mainnet' && matrix.config.network != 'joc-testnet' && matrix.config.network != 'linea-mainnet' && matrix.config.network != 'linea-sepolia'
