Update Verify logs with new approach

diff --git a/.github/workflows/sync-testnets.yml b/.github/workflows/sync-testnets.yml
--- a/.github/workflows/sync-testnets.yml
+++ b/.github/workflows/sync-testnets.yml
@@ -92,21 +92,26 @@ jobs:
       - name: Verify health of a node
         working-directory: sedge
         run: |
-          dockerLogs=$(docker compose logs execution)
+          dockerLogs=$(docker compose logs execution 2>/dev/null) || exit 10
       
-          countValid=$(echo "$dockerLogs" | grep -c "Valid. Result of a new payload:")
+          validLines=$(echo "$dockerLogs" | grep -E "Valid. Result of a new payload:") || exit 10
+          countValid=$(echo "$validLines" | wc -l)
           if [ $countValid -lt 1 ]; then
-            echo "Count of Valid: $countValid"
-            echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well." || exit 20
+            echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well."
+            exit 20
           fi
-          
-          count=$(echo "$dockerLogs" | grep -c -E "Invalid|Exception")
-          if [ $count -gt 0 ]; then
-            echo "Count of Invalid: $count"
+      
+          invalidLines=$(echo "$dockerLogs" | grep -E "Invalid|Exception") || exit 10
+          countInvalid=$(echo "$invalidLines" | wc -l)
+          if [ $countInvalid -gt 0 ]; then
             echo "Error: Lines found for 'Invalid' or 'Exception'"
-            echo "$dockerLogs" | grep -E "Invalid|Exception" || exit 30
+            echo "$invalidLines"
+            exit 30
           fi
-
+      
+          # If the script reaches this point, it means there were valid lines and no invalid lines.
+          echo "Valid lines:"
+          echo "$validLines"
           
   sepolia:
     name: "Run sync of sepolia testnet"
@@ -194,17 +199,23 @@ jobs:
       - name: Verify health of a node
         working-directory: sedge
         run: |
-          dockerLogs=$(docker compose logs execution)
+          dockerLogs=$(docker compose logs execution 2>/dev/null) || exit 10
       
-          countValid=$(echo "$dockerLogs" | grep -c "Valid. Result of a new payload:")
+          validLines=$(echo "$dockerLogs" | grep -E "Valid. Result of a new payload:") || exit 10
+          countValid=$(echo "$validLines" | wc -l)
           if [ $countValid -lt 1 ]; then
-            echo "Count of Valid: $countValid"
-            echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well." || exit 20
+            echo "Error: No lines found for 'Valid. Result of a new payload:' - probably node is not progressing well."
+            exit 20
           fi
-          
-          count=$(echo "$dockerLogs" | grep -c -E "Invalid|Exception")
-          if [ $count -gt 0 ]; then
-            echo "Count of Invalid: $count"
+      
+          invalidLines=$(echo "$dockerLogs" | grep -E "Invalid|Exception") || exit 10
+          countInvalid=$(echo "$invalidLines" | wc -l)
+          if [ $countInvalid -gt 0 ]; then
             echo "Error: Lines found for 'Invalid' or 'Exception'"
-            echo "$dockerLogs" | grep -E "Invalid|Exception" || exit 30
+            echo "$invalidLines"
+            exit 30
           fi
+      
+          # If the script reaches this point, it means there were valid lines and no invalid lines.
+          echo "Valid lines:"
+          echo "$validLines"
